In [0]:
import os
import matplotlib.pyplot as plt

import tensorflow as tf
# import tensorflow.contrib.eager as tfe

# tf.enable_eager_execution()

# print("TensorFlow version: {}".format(tf.VERSION))
# print("Eager execution: {}".format(tf.executing_eagerly()))

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [4]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving linkedin_developer_nlp_analysis.xlsx to linkedin_developer_nlp_analysis (4).xlsx
User uploaded file "linkedin_developer_nlp_analysis.xlsx" with length 61497 bytes


In [0]:
import numpy as np
import pandas as pd

In [6]:
!pip install xlrd

In [0]:
df = pd.read_excel("./linkedin_developer_nlp_analysis (4).xlsx")

In [8]:
df.head()

URL                    NAME  \
0           https://www.linkedin.com/in/saravanan90/     Saravanan Shanmugam   
1  https://www.linkedin.com/in/rajeshwar-dhayalan...      Rajeshwar Dhayalan   
2  https://www.linkedin.com/in/vigneshwara-manika...  vigneshwara manikandan   
3        https://www.linkedin.com/in/madhan-chandar/      Madhan Balachandar   
4  https://www.linkedin.com/in/karthik-venkatesh-...       Karthik Venkatesh   

                POSITION                                COMPANY NAME IN EXP  \
0  Full Stack Developer   An ardent learner getting exposed to new conce...   
1  Full Stack Developer   Looking towards the new technology and the get...   
2  Full Stack Developer   Experienced iOS App Developer with a demonstra...   
3  Full Stack Developer   I am an avid technology enthusiast. Skilled in...   
4   Full-Stack Developer  Full Stack developer with the ability to desig...   

                  Unnamed: 4  YEAR OF JOIN  PRESENT  TOTAL EXPER IN YEAR  \
0                   Tenmiles          2016        1                  4.7   
1                    ITILITE          2018        1                  2.4   
2                      Cisco          2017        1                  2.0   
3  Sirius Computer Solutions          2017        1                  0.1   
4                     Amazon          2013        1                  5.3   

                     LOCATION  \
0  Chennai, Tamil Nadu, India   
1  Vellore, Tamil Nadu, India   
2         Chennai Area, India   
3  Chennai, Tamil Nadu, India   
4  Chennai, Tamil Nadu, India   

                                          OTHER INFO  SKILL  OTHER SKILL  \
0  Web Developer Tech Lead,Web Developer,Java Tra...    NaN          NaN   
1  Working as Associate Software Engineer. As a S...    NaN          NaN   
2                                                NaN    NaN          NaN   
3                                                NaN    NaN          NaN   
4  ESTABLISHED an IMAGING LABS for developing sev...    NaN          NaN   

   TACT SKILL                 DATE  
0         NaN  2018-05-28 11:04:26  
1         NaN  2018-05-28 11:05:37  
2         NaN  2018-05-28 11:07:04  
3         NaN  2018-05-28 11:07:18  
4         NaN  2018-05-28 11:07:37

In [9]:
df['text'] = df['OTHER INFO'] +" "+ df['COMPANY NAME IN EXP']
df['text'][0]

'Web Developer Tech Lead,Web Developer,Java Trainee Web Developer An ardent learner getting exposed to new concepts and sticking to fundamentals, putting them into practice to bring out innovative ideas and solutions. Currently engaged in front end development and having fun and learning in the world of web.'

In [0]:
X = df['text']

In [11]:
X.fillna('.', inplace=True)
X

0      Web Developer Tech Lead,Web Developer,Java Tra...
1      Working as Associate Software Engineer. As a S...
2                                                      .
3                                                      .
4      ESTABLISHED an IMAGING LABS for developing sev...
5      Working as Full stack developer,Working as a W...
6      Full stack development comprising of Ruby on R...
7      We build awesome digital products that have th...
8       HappyFox Helpdesk Design and Development usin...
9                                                      .
10     Joined the company as the first employee. Deve...
11     ● Working as a Full Stack Developer at Tapzo s...
12     Java/J2EE developer and Part of Technology tea...
13     Full Stack Web Developer. Worked on maintainin...
14     Developing digital banking application for cli...
15     Specialized in Creating as well as integrating...
16                                                     .
17                             

In [12]:
position = df['POSITION'].str.lower()
position

0                                  full stack developer 
1                                  full stack developer 
2                                  full stack developer 
3                                  full stack developer 
4                                   full-stack developer
5                                  full stack developer 
6                                  full stack developer 
7                                   full stack developer
8                      full stack developer @ hippovideo
9                                  full stack developer 
10                              full stack developer | d
11                                 full stack developer 
12     full stack developer | java | elasticsearch | ...
13                       full stack developer @ gobumpr!
14                                  full stack developer
15                                (full stack developer)
16                                 full stack developer 
17                             

In [18]:
pos = [None] * len(position)
pos

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,

In [19]:
for i,j in enumerate(position.values):
  if "full" in j:
    pos[i] = "FullStack"
  elif "back" in j:
    pos[i] = "BackEnd"
  elif "ui" in j or "front" in j:
    pos[i] = "FrontEnd"
pos

['FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',

In [20]:
y = pos
y

['FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FullStack',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',
 'FrontEnd',

In [0]:
from sklearn.preprocessing import LabelBinarizer

In [56]:
encoder = LabelBinarizer()
transfomed_label = encoder.fit_transform(y)
print(transfomed_label)

[[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 

In [57]:
y = transfomed_label
encoder.classes_

array([0, 1, 2])

In [0]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [0]:
maxlen = 100
training_samples = 125
validation_samples = 49
max_words = 100

In [0]:
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)

In [27]:
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))
data = pad_sequences(sequences, maxlen=maxlen)
labels = np.asarray(y)
print('Shape of data tensor:', data.shape)
print('Shape of label tensor:', labels.shape)

Found 1839 unique tokens.
Shape of data tensor: (174, 100)
Shape of label tensor: (174, 3)


In [0]:
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]

In [0]:
x_train = data[:training_samples]
y_train = labels[:training_samples]
x_val = data[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]

In [45]:
print('x_train.shape', x_train.shape)
print('y_train.shape', y_train.shape)
print('x_val.shape', x_val.shape)
print('y_val.shape', y_val.shape)

x_train.shape (125, 100)
y_train.shape (125, 3)
x_val.shape (49, 100)
y_val.shape (49, 3)


In [31]:
train_dataset_url = "http://nlp.stanford.edu/data/glove.6B.zip"

train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),
                                           origin=train_dataset_url)

print("Local copy of the dataset file: {}".format(train_dataset_fp))

501620736/862182613 [================>.............] - ETA: 53s

862183424/862182613 [==============================] - 131s 0us/step
Local copy of the dataset file: /content/.keras/datasets/glove.6B.zip


In [32]:
!unzip {train_dataset_fp}

Archive:  /content/.keras/datasets/glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [33]:
!ls

datalab		   linkedin_developer_nlp_analysis (1).xlsx
glove.6B.100d.txt  linkedin_developer_nlp_analysis (2).xlsx
glove.6B.200d.txt  linkedin_developer_nlp_analysis (3).xlsx
glove.6B.300d.txt  linkedin_developer_nlp_analysis (4).xlsx
glove.6B.50d.txt   linkedin_developer_nlp_analysis.xlsx


In [34]:
embeddings_index = {}
f = open('./glove.6B.100d.txt')

for line in f:
  values = line.split()
  word = values[0]
  coefs = np.asarray(values[1:], dtype='float32')
  embeddings_index[word] = coefs
f.close()
print('Found %s word vectors.' % len(embeddings_index))

Found 400000 word vectors.


In [0]:
embedding_dim = 100
embedding_matrix = np.zeros((max_words, embedding_dim))

for word, i in word_index.items():
  if i < max_words:
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
      embedding_matrix[i] = embedding_vector

In [46]:
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense
model = Sequential()
model.add(Embedding(max_words, embedding_dim, input_length=maxlen))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 100, 100)          10000     
_________________________________________________________________
flatten_3 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_5 (Dense)              (None, 32)                320032    
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 99        
Total params: 330,131
Trainable params: 330,131
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.layers[0].set_weights([embedding_matrix])
model.layers[0].trainable = False

In [48]:
model.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['acc'])
history = model.fit(x_train, y_train,
epochs=100,
batch_size=32,
validation_data=(x_val, y_val))
model.save_weights('pre_trained_glove_model.h5')

Train on 125 samples, validate on 49 samples
Epoch 1/100
125/125 [==============================] - 0s 1ms/step - loss: 1.1964 - acc: 0.3680 - val_loss: 1.0080 - val_acc: 0.4490
Epoch 2/100
125/125 [==============================] - 0s 269us/step - loss: 0.9673 - acc: 0.3040 - val_loss: 0.9522 - val_acc: 0.4490
Epoch 3/100
125/125 [==============================] - 0s 293us/step - loss: 0.8932 - acc: 0.4240 - val_loss: 0.9412 - val_acc: 0.4490
Epoch 4/100
125/125 [==============================] - 0s 245us/step - loss: 0.8600 - acc: 0.4400 - val_loss: 0.9850 - val_acc: 0.4490
Epoch 5/100
125/125 [==============================] - 0s 248us/step - loss: 0.8322 - acc: 0.4640 - val_loss: 0.9770 - val_acc: 0.4490
Epoch 6/100
125/125 [==============================] - 0s 258us/step - loss: 0.8107 - acc: 0.4720 - val_loss: 0.9498 - val_acc: 0.4490
Epoch 7/100
125/125 [==============================] - 0s 252us/step - loss: 0.7967 - acc: 0.5360 - val_loss: 1.1699 - val_acc: 0.4490
Epoch 8/100


125/125 [==============================] - 0s 267us/step - loss: 0.6865 - acc: 0.5760 - val_loss: 0.9919 - val_acc: 0.3673
Epoch 24/100
125/125 [==============================] - 0s 265us/step - loss: 0.6861 - acc: 0.5680 - val_loss: 1.0044 - val_acc: 0.3673
Epoch 25/100
125/125 [==============================] - 0s 265us/step - loss: 0.6858 - acc: 0.6000 - val_loss: 1.0126 - val_acc: 0.3673
Epoch 26/100
125/125 [==============================] - 0s 224us/step - loss: 0.6856 - acc: 0.6000 - val_loss: 1.0065 - val_acc: 0.3673
Epoch 27/100
125/125 [==============================] - 0s 258us/step - loss: 0.6854 - acc: 0.6000 - val_loss: 1.0218 - val_acc: 0.3673
Epoch 28/100
125/125 [==============================] - 0s 251us/step - loss: 0.6852 - acc: 0.6000 - val_loss: 1.0226 - val_acc: 0.3673
Epoch 29/100
125/125 [==============================] - 0s 241us/step - loss: 0.6851 - acc: 0.6000 - val_loss: 1.0159 - val_acc: 0.3673
Epoch 30/100
125/125 [==============================] - 0s 25

125/125 [==============================] - 0s 263us/step - loss: 0.6842 - acc: 0.6000 - val_loss: 1.0493 - val_acc: 0.3673
Epoch 46/100
125/125 [==============================] - 0s 244us/step - loss: 0.6841 - acc: 0.6000 - val_loss: 1.0404 - val_acc: 0.3673
Epoch 47/100
125/125 [==============================] - 0s 272us/step - loss: 0.6841 - acc: 0.6000 - val_loss: 1.0469 - val_acc: 0.3673
Epoch 48/100
125/125 [==============================] - 0s 241us/step - loss: 0.6841 - acc: 0.6000 - val_loss: 1.0535 - val_acc: 0.3673
Epoch 49/100
125/125 [==============================] - 0s 246us/step - loss: 0.6840 - acc: 0.6000 - val_loss: 1.0570 - val_acc: 0.3673
Epoch 50/100
125/125 [==============================] - 0s 243us/step - loss: 0.6841 - acc: 0.6000 - val_loss: 1.0680 - val_acc: 0.3673
Epoch 51/100
125/125 [==============================] - 0s 249us/step - loss: 0.6840 - acc: 0.6000 - val_loss: 1.0659 - val_acc: 0.3673
Epoch 52/100
125/125 [==============================] - 0s 27

125/125 [==============================] - 0s 280us/step - loss: 0.6837 - acc: 0.6000 - val_loss: 1.0849 - val_acc: 0.3673
Epoch 68/100
125/125 [==============================] - 0s 267us/step - loss: 0.6838 - acc: 0.6000 - val_loss: 1.0930 - val_acc: 0.3673
Epoch 69/100
125/125 [==============================] - 0s 283us/step - loss: 0.6837 - acc: 0.6000 - val_loss: 1.0795 - val_acc: 0.3673
Epoch 70/100
125/125 [==============================] - 0s 277us/step - loss: 0.6837 - acc: 0.6000 - val_loss: 1.0839 - val_acc: 0.3673
Epoch 71/100
125/125 [==============================] - 0s 270us/step - loss: 0.6837 - acc: 0.6000 - val_loss: 1.0934 - val_acc: 0.3673
Epoch 72/100
125/125 [==============================] - 0s 264us/step - loss: 0.6837 - acc: 0.6000 - val_loss: 1.0952 - val_acc: 0.3673
Epoch 73/100
125/125 [==============================] - 0s 267us/step - loss: 0.6837 - acc: 0.6000 - val_loss: 1.0880 - val_acc: 0.3673
Epoch 74/100
125/125 [==============================] - 0s 27

125/125 [==============================] - 0s 258us/step - loss: 0.6837 - acc: 0.6000 - val_loss: 1.0976 - val_acc: 0.3673
Epoch 92/100
125/125 [==============================] - 0s 278us/step - loss: 0.6836 - acc: 0.6000 - val_loss: 1.0973 - val_acc: 0.3673
Epoch 93/100
125/125 [==============================] - 0s 249us/step - loss: 0.6835 - acc: 0.6000 - val_loss: 1.0967 - val_acc: 0.3673
Epoch 94/100
125/125 [==============================] - 0s 279us/step - loss: 0.6836 - acc: 0.6000 - val_loss: 1.0955 - val_acc: 0.3673
Epoch 95/100
125/125 [==============================] - 0s 316us/step - loss: 0.6836 - acc: 0.6000 - val_loss: 1.1003 - val_acc: 0.3673
Epoch 96/100
125/125 [==============================] - 0s 288us/step - loss: 0.6835 - acc: 0.6000 - val_loss: 1.1018 - val_acc: 0.3673
Epoch 97/100
125/125 [==============================] - 0s 276us/step - loss: 0.6835 - acc: 0.6000 - val_loss: 1.1061 - val_acc: 0.3673
Epoch 98/100
125/125 [==============================] - 0s 27

In [0]:
testing = ["Experienced iOS App Developer with a demonstrated history of working in the information technology and services industry. Skilled in Object-Oriented Programming (OOP), WebGL, Microsoft Excel, Java, and Microsoft Word. Strong engineering professional with a Bachelor of Engineering - BE ocused in Computer Science from Thiagarajar College of Engineering"]

In [0]:
def token_hot(text):
  
  text = np.array(text)
  
  tokenizer = Tokenizer(num_words=1000)
  tokenizer.fit_on_texts(text)
  sequences = tokenizer.texts_to_sequences(text)
  
  word_index = tokenizer.word_index
  print('Found %s unique tokens.' % len(word_index))
  
  data = pad_sequences(sequences, maxlen=100)
  print('Shape of data tensor:', data.shape)
  return data

In [61]:
checknew = (token_hot(testing))

Found 38 unique tokens.
Shape of data tensor: (1, 100)


In [62]:
model.predict_classes(checknew)

array([2])